export const ROUTES = {
  HOME: '/',
  MAIN: '/main',
  LOGIN: '/login',
  AUTH: '/auth',
  ADMIN: '/admin',
  SEARCH_RAW: '/search/',
  SEARCH: '/search/:query',
  BEST_RAW: '/best/',
  BEST: '/best/:category',
  RESTAURANT_RAW: '/resturant/',
  RESTAURANT: '/resturant/:resturantno',
  RESTAURANT_RESERVATION: '/reservation',
  MYPAGE_HOME: '/mypage',
  MYPAGE_MAIN: '/mypage/main',
  MYPAGE_HISTORY: '/mypage/history',
  MYPAGE_BOOKMARK: '/mypage/bookmark',
  MYPAGE_REVISE: '/mypage/revise',
  MYPAGE_DROP: '/mypage/drop',
  OTHERS: '*',
};
